spring:
  application:
    name: max-gateway
  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: max-auth
          uri: lb://max-auth
          predicates:
            - Path=/auth/**

      routes:
        - id: max-accounts
          uri: lb://max-accounts
          predicates:
            - Path=/accounts/**

management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: ['*']

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:${EUREKA_URI:http://localhost:8761/eureka/}

api:
  endpoints:
    open: >
      POST /auth/register/,
      POST /auth/login/,
      ANY /auth/actuator/**,
      ANY /accounts/actuator/,