spring:
  application:
    name: max-gateway
  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: max-auth
          uri: lb://max-auth
          predicates:
            - Path=/auth/**

        - id: max-account
          uri: lb://max-account
          predicates:
            - Path=/accounts/**
        
        - id: max-product
          uri: lb://max-product
          predicates:
            - Path=/products/**

management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: ['*', 'prometheus']

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:${EUREKA_URI:http://localhost:8761/eureka/}

api:
  endpoints:
    open: >
      POST /auth/register,
      POST /auth/login,

      ANY /auth/actuator,
      ANY /auth/actuator/**,
      ANY /accounts/actuator,
      ANY /accounts/actuator/**,
      ANY /products/actuator,
      ANY /products/actuator/**,

      ANY /accounts/swagger-ui,
      ANY /accounts/swagger-ui/**,
      ANY /accounts/v3/api-docs,
      ANY /products/swagger-ui,
      ANY /products/swagger-ui/**,
      ANY /products/v3/api-docs,
      ANY /auth/swagger-ui,
      ANY /auth/swagger-ui/**,
      ANY /auth/v3/api-docs,
      ANY /gateway/swagger-ui,
      ANY /gateway/swagger-ui/**,
      ANY /gateway/v3/api-docs